services:
  dev:
    container_name: ai-assistants-dev
    image: alexfariakof/jail-container:latest
    volumes:
      - ../../monoRepo:/monoRepo
      - ../../workspace:/workspaces
      - node_modules:/workspaces/angular-app/node_modules
      - angular_cache:/workspaces/angular-app/.angular
    ports:
      - "9877:9876"
      - "5001:5000"
      - "4201:4200"
    command: /bin/bash
    shm_size: "2g"
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "1"
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

volumes:
  node_modules:
  angular_cache:
